parameters:
    # ldap params -- @TODO MOVE THESE SOMEPLACE BETTER
    daps_ldap.ldap.host: ldap://example.com
    daps_ldap.ldap.port: 389
    daps_ldap.ldap.dn: uid
    daps_ldap.ldap.username_suffix: ou=people,dc=example,dc=com
    # userprovider param
    daps_ldap_user_provider.inactive_key_value: shadowflag=0
    # class parameters
    daps_ldap.user_provider.class: Daps\LdapBundle\Security\User\LdapUserProvider
    daps_ldap.authentication_provider.class: Daps\LdapBundle\Security\Authentication\Provider\LdapAuthenticationProvider
    security.user_checker.class: Symfony\Component\Security\Core\User\UserChecker
    daps_ldap.ldap.class: Daps\LdapBundle\Security\Ldap\Ldap
    
services:
    security.user_checker:
        class: %security.user_checker.class%
        
    daps_ldap_user_provider:
        class: %daps_ldap.user_provider.class%
        arguments: [@daps_ldap.ldap, %daps_ldap_user_provider.inactive_key_value%]

    daps_ldap.security.authentication.provider:
        class: %daps_ldap.authentication_provider.class%
        arguments: ['', @security.user_checker , '', %security.authentication.hide_user_not_found% ]
        
    daps_ldap.ldap:
        class: %daps_ldap.ldap.class%
        arguments: [%daps_ldap.ldap.host%, %daps_ldap.ldap.port%, %daps_ldap.ldap.dn%, %daps_ldap.ldap.username_suffix%]